<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <!-- <script src="./0.MyPromise.js"></script> -->
    <script src="./5.防止值的穿透问题.js"></script>
    <!-- <script src="./MyPromise.js"></script> -->
    <!-- <script src="./MyPromise_2.js"></script> -->

    <script>
        var pro1 = new MyPromise((resolve, reject) => {
                setTimeout(() => {
                    resolve(1);
                    // reject(2);
                }, 1000);
            })
            .then(undefined, data => { //只处理了正常情况,但现在pro1是reject,所以不执行thenable
                console.log(data);
            })
            .catch(err => { //
                console.log(err); //2,因为then中没有传入thenable
            }).then(data => {
                console.log('ccc', data);
                console.log('tttt')
            })

        //当pro1resolve之后
        // var pro2 = pro1.catch(err => { //不会运行这个catch函数,因为1s后pro1是resolve
        //     //所以这个pro2应该得到的是pro1的fulfilled
        //     //但是父亲(pro1)并没有传递这个状态给子pro2,所以我们需要在代码中处理好
        //     console.log(err);
        // }); //去控制台输入pro2检验状态是否为fulfilled,是,所以我们解决了问题
    </script>
</body>

</html>